data = [
    {'name': 'Cristiano Ronaldo', 'country': 'Portugal', 'description': 'Footballer', 'follower_account': 215},
    {'name': 'Lionel Messi', 'country': 'Argentina', 'description': 'Footballer', 'follower_account': 215},
    {'name': 'Neymar Jr.', 'country': 'Brazil', 'description': 'Footballer', 'follower_account': 215},
    {'name': 'Taylor Swift', 'country': 'USA', 'description': 'Singer-songwriter', 'follower_account': 188},
    {'name': 'Dwayne Johnson', 'country': 'USA', 'description': 'Actor and Former Wrestler', 'follower_account': 210},
    {'name': 'Kim Kardashian', 'country': 'USA', 'description': 'Television Personality and Businesswoman', 'follower_account': 177},
    {'name': 'Ariana Grande', 'country': 'USA', 'description': 'Singer and Actress', 'follower_account': 174},
    {'name': 'Selena Gomez', 'country': 'USA', 'description': 'Singer and Actress', 'follower_account': 169},
    {'name': 'Kylie Jenner', 'country': 'USA', 'description': 'Businesswoman and Social Media Personality', 'follower_account': 180},
    {'name': 'LeBron James', 'country': 'USA', 'description': 'Basketball Player', 'follower_account': 150},
    {'name': 'Justin Bieber', 'country': 'Canada', 'description': 'Singer', 'follower_account': 168},
    {'name': 'Billie Eilish', 'country': 'USA', 'description': 'Singer-songwriter', 'follower_account': 145},
    {'name': 'Shakira', 'country': 'Colombia', 'description': 'Singer-songwriter', 'follower_account': 130},
    {'name': 'Katy Perry', 'country': 'USA', 'description': 'Singer', 'follower_account': 120},
    {'name': 'Rihanna', 'country': 'Barbados', 'description': 'Singer and Businesswoman', 'follower_account': 125},
    {'name': 'Beyoncé', 'country': 'USA', 'description': 'Singer-songwriter', 'follower_account': 130},
    {'name': 'Drake', 'country': 'Canada', 'description': 'Rapper', 'follower_account': 115},
    {'name': 'Ellen DeGeneres', 'country': 'USA', 'description': 'Television Host', 'follower_account': 120},
    {'name': 'Kanye West', 'country': 'USA', 'description': 'Rapper and Fashion Designer', 'follower_account': 110},
    {'name': 'Elon Musk', 'country': 'USA', 'description': 'Entrepreneur', 'follower_account': 140},
    {'name': 'Jennifer Lopez', 'country': 'USA', 'description': 'Singer and Actress', 'follower_account': 150},
    {'name': 'Lady Gaga', 'country': 'USA', 'description': 'Singer-songwriter', 'follower_account': 130},
    {'name': 'Tom Cruise', 'country': 'USA', 'description': 'Actor', 'follower_account': 100},
    {'name': 'David Beckham', 'country': 'UK', 'description': 'Footballer', 'follower_account': 110},
    {'name': 'Gal Gadot', 'country': 'Israel', 'description': 'Actress', 'follower_account': 110},
    {'name': 'Shawn Mendes', 'country': 'Canada', 'description': 'Singer-songwriter', 'follower_account': 105},
    {'name': 'Will Smith', 'country': 'USA', 'description': 'Actor', 'follower_account': 120},
    {'name': 'Zendaya', 'country': 'USA', 'description': 'Actress and Singer', 'follower_account': 115},
    {'name': 'Chris Hemsworth', 'country': 'Australia', 'description': 'Actor', 'follower_account': 110},
    {'name': 'Vin Diesel', 'country': 'USA', 'description': 'Actor', 'follower_account': 100},
    {'name': 'Johnny Depp', 'country': 'USA', 'description': 'Actor', 'follower_account': 105},
    {'name': 'Emma Watson', 'country': 'UK', 'description': 'Actress', 'follower_account': 100},
    {'name': 'Miley Cyrus', 'country': 'USA', 'description': 'Singer and Actress', 'follower_account': 125},
    {'name': 'Ed Sheeran', 'country': 'UK', 'description': 'Singer-songwriter', 'follower_account': 130},
    {'name': 'Harry Styles', 'country': 'UK', 'description': 'Singer and Actor', 'follower_account': 110},
    {'name': 'Nicki Minaj', 'country': 'Trinidad and Tobago', 'description': 'Rapper', 'follower_account': 105},
    {'name': 'Adele', 'country': 'UK', 'description': 'Singer-songwriter', 'follower_account': 120},
    {'name': 'Margot Robbie', 'country': 'Australia', 'description': 'Actress', 'follower_account': 110},
    {'name': 'Gigi Hadid', 'country': 'USA', 'description': 'Model', 'follower_account': 75},
    {'name': 'Kendall Jenner', 'country': 'USA', 'description': 'Model and Television Personality', 'follower_account': 90},
    {'name': 'Priyanka Chopra', 'country': 'India', 'description': 'Actress', 'follower_account': 95},
    {'name': 'Robert Downey Jr.', 'country': 'USA', 'description': 'Actor', 'follower_account': 120},
    {'name': 'Chris Evans', 'country': 'USA', 'description': 'Actor', 'follower_account': 105},
    {'name': 'Scarlett Johansson', 'country': 'USA', 'description': 'Actress', 'follower_account': 110},
    {'name': 'Cardi B', 'country': 'USA', 'description': 'Rapper', 'follower_account': 100},
    {'name': 'Bruno Mars', 'country': 'USA', 'description': 'Singer-songwriter', 'follower_account': 90},
    {'name': 'Hugh Jackman', 'country': 'Australia', 'description': 'Actor', 'follower_account': 95},
    {'name': 'Keanu Reeves', 'country': 'Canada', 'description': 'Actor', 'follower_account': 110},
    {'name': 'Emma Stone', 'country': 'USA', 'description': 'Actress', 'follower_account': 90},
    {'name': 'Sophie Turner', 'country': 'UK', 'description': 'Actress', 'follower_account': 85},
    {'name': 'Zac Efron', 'country': 'USA', 'description': 'Actor', 'follower_account': 90},
    {'name': 'Blake Lively', 'country': 'USA', 'description': 'Actress', 'follower_account': 85},
    {'name': 'Ryan Reynolds', 'country': 'Canada', 'description': 'Actor', 'follower_account': 100},
    {'name': 'Jason Momoa', 'country': 'USA', 'description': 'Actor', 'follower_account': 85},
    {'name': 'Anne Hathaway', 'country': 'USA', 'description': 'Actress', 'follower_account': 95},
    {'name': 'Daniel Radcliffe', 'country': 'UK', 'description': 'Actor', 'follower_account': 85},
    {'name': 'Tom Hiddleston', 'country': 'UK', 'description': 'Actor', 'follower_account': 90},
    {'name': 'Joaquin Phoenix', 'country': 'USA', 'description': 'Actor', 'follower_account': 75},
    {'name': 'Tom Holland', 'country': 'UK', 'description': 'Actor', 'follower_account': 95},
    {'name': 'Jason Statham', 'country': 'UK', 'description': 'Actor', 'follower_account': 85},
    {'name': 'Gal Gadot', 'country': 'Israel', 'description': 'Actress', 'follower_account': 110},
    {'name': 'Mark Ruffalo', 'country': 'USA', 'description': 'Actor', 'follower_account': 80},
    {'name': 'Jeremy Renner', 'country': 'USA', 'description': 'Actor', 'follower_account': 75},
    {'name': 'Jennifer Lawrence', 'country': 'USA', 'description': 'Actress', 'follower_account': 100},
    {'name': 'Christian Bale', 'country': 'UK', 'description': 'Actor', 'follower_account': 75},
    {'name': 'Ben Affleck', 'country': 'USA', 'description': 'Actor', 'follower_account': 80},
    {'name': 'Brad Pitt', 'country': 'USA', 'description': 'Actor', 'follower_account': 90},
    {'name': 'Leonardo DiCaprio', 'country': 'USA', 'description': 'Actor', 'follower_account': 110},
    {'name': 'Natalie Portman', 'country': 'USA', 'description': 'Actress', 'follower_account': 85},
    {'name': 'Reese Witherspoon', 'country': 'USA', 'description': 'Actress', 'follower_account': 90},
    {'name': 'Sofia Vergara', 'country': 'Colombia', 'description': 'Actress', 'follower_account': 85}
]
