# SCREEN
APP_TITLE="PONG"
SCREEN_HEIGHT = 700
SCREEN_WIDTH = 1200
SCREEN_BGCOLOR = "black"
SCREEN_GAP=40
SCREEN_LIMIT_HEIGHT = int(SCREEN_HEIGHT/2 - SCREEN_GAP)
SCREEN_LIMIT_WIDTH = int(SCREEN_WIDTH/2 - SCREEN_GAP)
GAME_SPEED= 0.1
#BALL
BALL_SHAPE = "circle"
BALL_COLOR = "white"
BALL_X_POS=10
BALL_Y_POS=10

#PADDLE
PADDLE_COLOR = "white"
PADDLE_SHAPE = "square"
PADDLE_WIDTH = 10
PADDLE_WID=5
PADDLE_LEN=1