# SCREEN
APP_TITLE="PONG"
SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800
SCREEN_BGCOLOR = "black"
SCREEN_GAP= 80
SCREEN_LIMIT_HEIGHT = int(SCREEN_HEIGHT/2 - 20)
SCREEN_LIMIT_WIDTH = int(SCREEN_WIDTH/2 - SCREEN_GAP)
GAME_SPEED= 0.1
#BALL
BALL_SHAPE = "circle"
BALL_COLOR = "white"
BALL_X_POS=10
BALL_Y_POS=10

#PADDLE
PADDLE_GAP= 50
PADDLE_POSSTION = int(SCREEN_WIDTH/2 - PADDLE_GAP)
PADDLE_COLOR = "white"
PADDLE_SHAPE = "square"
PADDLE_WIDTH = 10
PADDLE_WID=5
PADDLE_LEN=1
PADDLE_MISSED= int(SCREEN_WIDTH/2 - 20)